### ISSUE TITLE
Demo please?

### ISSUE THREAD

**Issue by tnrich** [NoHomey/material-ui-number-input#1]

**Comment by NoHomey** [comment]
You can check the [example](https://github.com/NoHomey/material-ui-number-input/tree/master/example) and play with it. Currently there is no live demo like github page but I will add one within a week.

**Comment by tnrich** [comment]
Thanks!

**Comment by NoHomey** [comment]
@tnrich the live demo is ready, check [project's github page](http://nohomey.github.io/material-ui-number-input).

**Comment by tnrich** [comment]
Thanks Ivo!
