### ISSUE TITLE
Dependency on material-ui 0.17.x

### ISSUE THREAD

**Issue by ghost** [NoHomey/material-ui-number-input#10]
material-ui-number-input specifies a dependency on material-ui  of ^0.17.x which effectively locks the dependency to the older 0.17.* versions of material-ui, and in turn locks any application that uses number-input.

If that in not intentional, and versions 0.18.* are compatible, the dependency could be specified as  >0.17.1 instead.

**Comment by NoHomey** [comment]
I did update all the dependencies. Thanks for the issue and sorry for the delay. I was really busy lately.
