### ISSUE TITLE
Remove propTypes or use prop-types package instead

### ISSUE THREAD

**Issue by lamuertepeluda** [NoHomey/material-ui-number-input#11]
With React 15.5+

`warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

More on this on the [official React documentation page](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)

The culprit is [this line here](https://github.com/NoHomey/material-ui-number-input/blob/master/src/NumberInput.tsx#L192).

**Comment by NoHomey** [comment]
Thanks I migrate to it with latest release. I will update changelog after 5/6 hours.
