### ISSUE TITLE
Empty material-ui-number-input folder in node_modules

### ISSUE THREAD

**Issue by acherkashin** [NoHomey/material-ui-number-input#9]
When I install this package he is empty. Why?
![image](https://cloud.githubusercontent.com/assets/9947582/25062571/1ab90040-21d7-11e7-9a24-aae3ad7f9ed1.png)

**Comment by NoHomey** [comment]
Yea sry I've created a dummy version yesterday to sync github and npm versions but forgot to run a command before publishing. My my apologies. I've fix it: https://github.com/NoHomey/material-ui-number-input/blob/master/CHANGELOG.md#v5019.
